baseURL = "https://ayg0.github.io/gettoknow.github.io/"
title = "GetToKnow"
languageCode = "en"
DefaultContentLanguage = "en"
theme = "hugo-theme-m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  avatar = "ProgrammerHood.jpeg"
  author = "Taha Ed-dafili"
  description = "Enjoy your tour, as it's will be an interesting one."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/Ayg0"
  [[params.social]]
    icon = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/taha-ed-dafili-a17779213/"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
  
  # Test theme
[params.style]
  darkestColor = "#242930"
  darkColor = "#313841"
  lightColor = "#CBD2D8"
  lightestColor = "#ffffff"
  primaryColor = "#65D2DA"
